"""
Django settings for dating project.

Generated by 'django-admin startproject' using Django 1.11.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from django.conf import settings

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!o79bu252ub-87-g7tl1xequw%6+drcxwh*3xy$ssbezo9&bs='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [

    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'account',
    'search',
    'django_messages',
    'friendship',
    'social_django',
    # 'pinax.notifications',
    # 'django_private_chat.apps.DjangoPrivateChatConfig',
    'django.contrib.admin',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',

]

ROOT_URLCONF = 'dating.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'Template')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',

                'social_django.context_processors.login_redirect',
            ],
            # 'libraries':{
            #     'friendshiptags': 'dating.templatetags.friendshiptags',

            # }
        },
    },
]

WSGI_APPLICATION = 'dating.wsgi.application'
CHAT_WS_SERVER_HOST = 'www.rightone.com'
CHAT_WS_SERVER_PORT = 5002
CHAT_WS_SERVER_PROTOCOL = 'ws'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
from django.core.urlresolvers import reverse_lazy
LOGIN_REDIRECT_URL = reverse_lazy('dashboard')
LOGIN_URL = reverse_lazy('login')
LOGOUT_URL = reverse_lazy('logout')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')


AUTH_PROFILE_MODULE = 'account.Profile'

AUTHENTICATION_BACKENDS = (
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.twitter.TwitterOAuth',
    'social_core.backends.google.GoogleOAuth2',

    'django.contrib.auth.backends.ModelBackend',
    'account.authentication.EmailAuthBackend',
   # 'social.backends.facebook.Facebook2OAuth2',

)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
ALLOWED_HOSTS = ['www.rightone.com', '127.0.0.1','[::1]']
SOCIAL_AUTH_FACEBOOK_API_VERSION = '2.7'
SOCIAL_AUTH_FACEBOOK_KEY = '863861190450713'
SOCIAL_AUTH_FACEBOOK_SECRET = 'caed81a524ca6c54f70af17431c31001'
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
SOCIAL_AUTH_TWITTER_KEY = '43okFKdpXbfsDbIs6UzJJTw2x' # Twitter Consumer Key
SOCIAL_AUTH_TWITTER_SECRET = 'Sh2j3DHl8XPHjcKwXnWX3LBuxwCWzdWcCW79DTcKqMY22fiAmP' # Twitter Consumer Secret
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '585089539351-vasmn8pprbagkjf1e4ma3fv8skruf1lh.apps.googleusercontent.com' # Google Consumer Key
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '-LpHX1FZ_6X4wYuGAd1_K03i' # Google Consumer Secret
SOCIAL_AUTH_GITHUB_KEY = 'c21e94c9c9cc5e0a6bb1'
SOCIAL_AUTH_GITHUB_SECRET = 'b20af5469b0f5af35d7e867d5d62f85627d55547'
# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/
SITE_ID = 4
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
