# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 16:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smoking', models.IntegerField(choices=[(0, 'Never smoked'), (1, 'Tried smoking'), (3, 'Former smoker'), (4, 'Current smoker')], default=0)),
                ('drinking', models.IntegerField(choices=[(0, 'Never'), (1, 'Social drinker'), (2, 'Drink a lot')], default=0)),
                ('health_lifesty', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='hobbies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='spend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_all', models.IntegerField(default=0)),
                ('shopping_center', models.IntegerField(default=0)),
                ('branded_clothing', models.IntegerField(default=0)),
                ('partying_socializing', models.IntegerField(default=0)),
                ('appearance', models.IntegerField(default=0)),
                ('gadgets', models.IntegerField(default=0)),
                ('food', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userfeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enjoymusic', models.IntegerField(default=0)),
                ('enjoymovie', models.IntegerField(default=0)),
                ('hobbies', models.ManyToManyField(blank=True, to='search.hobbies')),
                ('moviehated', models.ManyToManyField(blank=True, related_name='hmovie', to='search.movie')),
                ('movieloved', models.ManyToManyField(blank=True, related_name='lmovie', to='search.movie')),
                ('musichated', models.ManyToManyField(blank=True, related_name='hmusic', to='search.music')),
                ('musicloved', models.ManyToManyField(blank=True, related_name='lmusic', to='search.music')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
